language: cpp

sudo: enabled

compiler:
  - gcc

matrix:
  include:
    - name: CUDA 9.2
      env:
      - CUDA=9.2.148-1
      - CUDA_SHORT=9.2
      - CUDA_APT=9-2
      - UBUNTU_VERSION=ubuntu1604
      dist: xenial
    - name: CUDA 10.1
      env:
      - CUDA=10.1.105-1
      - CUDA_APT=10-1
      - CUDA_SHORT=10.1
      - UBUNTU_VERSION=ubuntu1804
      dist: bionic
    - name: CUDA 10.2
      env:
      - CUDA=10.2.89-1
      - CUDA_APT=10-2
      - CUDA_SHORT=10.2
      - UBUNTU_VERSION=ubuntu1804
      dist: bionic

before_install:
  - CUDA_REPO_PKG=cuda-repo-${UBUNTU_VERSION}_${CUDA}_amd64.deb
  - wget http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${CUDA_REPO_PKG}
  - sudo dpkg -i ${CUDA_REPO_PKG}
  - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
  - sudo apt-key add 7fa2af80.pub
  - sudo apt update -qq
  - sudo apt install -y cuda-drivers cuda-core-${CUDA_APT} cuda-cudart-dev-${CUDA_APT} cuda-nvtx-${CUDA_APT}
  - sudo apt clean
  - CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
  - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${CUDA_HOME}/lib64/stubs:/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}
  - PATH=${CUDA_HOME}/bin:${PATH}
  
before_script:
    - mkdir build; cd build; cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON ..

script: 
    - VERBOSE=1 make
